version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build: ./backend
    depends_on:
      - mongo
      - redis
      - kafka
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/airport_ops
      - JWT_SECRET=devsecret
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:29092
      - CORS_ORIGIN=http://localhost:5173
      - ADMIN_EMAIL=admin@airport.local
      - ADMIN_PASSWORD=ChangeMe123!
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:4000
      - VITE_WS_BASE=http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mongo_data: {}

